name: TestRegression

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "prod"
      arguments:
        required: false
        default: "-m regression"

jobs:
  playwright:
    name: Regression tests
    runs-on: ubuntu-24.04
    env:
      AUTH_LOGIN: ${{ secrets.AUTH_LOGIN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
    
    strategy:
      matrix:
        browser: [chromium]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Playwright system dependencies
        uses: microsoft/playwright-github-action@v1
        with:
          browsers: chromium

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright pytest-playwright

      - name: Run tests
        run: pytest ${{ inputs.arguments }} --bn ${{ matrix.browser }} --headless true
