name: TestRegression

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "prod"
        description: "Set environment, e.g. `ENV=prod or ENV=shot`"
      arguments:
        required: false
        default: "-m regression"
        description: "pytest additional arguments, e.g. `-m regression`"

jobs:
  playwright:
    name: Regression tests
    runs-on: ubuntu-24.04  # Используем свежую ОС
    env:
      AUTH_LOGIN: ${{ secrets.AUTH_LOGIN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
    strategy:
      matrix:
        browser: [remote_chrome]  # Изменено с remote_chrome на локальный браузер
    outputs:
      env_name: ${{ steps.set_env.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libappindicator3-1 libsecret-1-0 libgbm-dev

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m playwright install --with-deps chromium

      - name: Set environment variables
        id: set_env
        run: |
          if [ "${{github.event_name}}" = "schedule" ]; then
            args="-m regression"
            ENV="prod"
          else
            ENV='${{github.event.inputs.environment}}'
            args='${{github.event.inputs.arguments}}'
          fi
          echo "env_name=$ENV" >> $GITHUB_OUTPUT
          echo "ARGS=$args" >> $GITHUB_ENV

      - name: Run tests
        run: pytest ${{ env.ARGS }} --bn ${{ matrix.browser }}
